#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=6:00:00
#PBS -N mrtrix3_act
#PBS -V

echo "Tracking data..."
time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./mrtrix3_tracking.sh

## check for the output for success
if [ ! -f track.tck ]; then
    echo "Final tractography file missing."
    exit 1
fi

